export const APP_CONSTANTS = {
  API: {
    ENDPOINTS: {
      PRODUCTS: 'products',
      PHARMACIES: 'pharmacies',
      CATEGORIES: 'categories',
      PHARMACY: 'pharmacy',
      PHARMACY_SENDREQUEST: 'Pharmacy/SendRequestAddDrug',
      PHARMACY_ACTIVE: 'Pharmacy/GetPharmaciesByStatus/1',
      PHARMACY_STOCK: 'PharmacyStock',
      PHARMACY_STOCK_ALL: 'PharmacyStock/allPharmaciesStock',
      BATCH_PHARMACY_STOCK_BY_ID: 'PharmacyStock/GetBatchOfPharmacyStock',
      GET_ALLINVENTORY: 'PharmacyStock/AllInventory',
      PHARMACYSTOCK_INVENTORY_STATUS_BY_ID: 'PharmacyStock/InventoryStatusByID',
      PHARMACYSTOCK_SEARCH_ALL: 'PharmacyStock/SearchFor',
      SEARCH: 'search',
      ACCOUNT_REGISTER: 'Account/Register',
      ACCOUNT_LOGIN: 'Account/Login',
      ACCOUNT_VERIFY_TOKEN: 'Account/VerifyToken',
      DRUG_CATEGORY: 'Drug/Category',
      DRUG_RANDOM: 'Drug/2',
      DRUG_BY_ID: 'Drug',
      DRUG_SEARCH: 'Drug/Search',
      DRUG_ADMINDATA: 'Drug/GetAdminData',
      FAVORITES: 'favorites',
      ORDERS_SUBMIT: 'Orders/submit',
      ORDER_SUMMARY: 'Orders/order-summary',
      ORDERS_CREATE_CHECKOUT_SESSION: 'Orders/CreateCheckoutSession',
      PATIENT_PROFILE: 'Patient/Profile',
      PATIENT_PROFILE_EDIT: 'Patient/UpdateProfile',
      PATIENT_MEDICAL_INFO: 'Patient/MedicalInfo',
      PHARMACY_ANALYSIS: 'Orders/analysis',
      PHARMACY_STOCK_ANALYSIS: 'PharmacyStock/InventoryStatusByID',
      ORDERS_VALIDATE_SESSION: 'Orders/validate-session',
      MULTIPLE_FAVORITES: 'Favorites/AddMultiple',
      ADMIN_ANALYSIS:'Orders/allOrdersAnalysis',
      PHARMACY_STATUS: 'Pharmacy/GetPharmaciesByStatus',
      PHARMACIES_SUMMARY:'Orders/pharmacies-summary',
      CONFIRM_PHARMACY: 'Pharmacy/ConfirmPharmacy',
      SUSPEND_PHARMACY: 'Pharmacy/SuspendedPharmacy',
      REJECT_PHARMACY: 'Pharmacy/RejectPharmacy',
      CHANGE_ROLE: 'Role/changeRoleByPharmacy',


    },
  },
  environment: {
    production: true,
    apiBaseUrl: 'http://localhost:5278/api',
    apiVersion: 'v1',
    appName: 'PharmaLink',
    googleApiKey: 'AIzaSyCsSmpYJNb9htQSnH1NM-yHmM4bOSzZnUU',
    features: {
      enableNotifications: true,
      enableGeolocation: true,
      maxNearbyPharmacies: 10,
    },
  },

  ErrorCodes: {
    DIFFERENT_PHARMACY: 'DIFFERENT_PHARMACY',
  },
  Cart: 'Cart',
  Favorites: 'Favorites'
};
